### ISSUE TITLE
Bug Fix

### ISSUE THREAD

**Issue by JYSerrano** [AkshayChordiya/CounterViewModelDemo#2]
Good Morning

I am doing your Android Architecture Components course and I've found a bug in your app.

Actually, it's printing the MutableLiveData address and not the number as you can see in the image below:

![bug](https://user-images.githubusercontent.com/24799624/55379203-9a5b3c00-54f2-11e9-910e-044efcd29e2f.png)

For fix this problem, I've just assigned the values that comes with the observer into the count.text and not calling the counterViewModel.counter.toString, changing this I've fixed this problem, as you can see in the image below:

![fix](https://user-images.githubusercontent.com/24799624/55379208-9f1ff000-54f2-11e9-8dfd-809ddcec1c23.png)

I've created a pull request with the fix. 

I hope to hear from you soon

**Comment by AkshayChordiya** [comment]
Fixed with #1
